AUT=testQML
ENVVARS=envvars
HOOK_SUB_PROCESSES=false
IMPLICITAUTSTART=0
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES=tst_case1 tst_application_loop tst_multiple_aut tst_import_function tst_signal_handler tst_log_text tst_handle_combobox tst_object_search tst_case2 tst_case10
VERSION=3
WRAPPERS=Qt
